spring:
  application:
    # This ends up as the service name in zipkin
    name: mockdb
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    async:
      enabled: false
    sampler:
      percentage: 1.0
